# -*- coding: utf-8 -*-
"""AI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IAskfmgMPkEUAgXkIkkuaa1baL6MWYeT
"""

# Commented out IPython magic to ensure Python compatibility.
import nsepy as NSE
from datetime import date
# %matplotlib inline
import matplotlib.pyplot as plot
import pandas as pd

!pip install nsepy

data=NSE.get_history(symbol='INFY',start=date(2015,1,1),end=date(2019,8,26))
data['Close'].plot()

data2=NSE.get_history(symbol='YESBANK',start=date(2015,1,1),end=date(2019,8,26))

data3=NSE.get_history(symbol='HEROMOTOCO',start=date(2015,1,1),end=date(2019,8,26))
data4=NSE.get_history(symbol='KOTAKBANK',start=date(2015,1,1),end=date(2019,8,26))
data5=NSE.get_history(symbol='EICHERMOT',start=date(2015,1,1),end=date(2019,8,26))
data6=NSE.get_history(symbol='RELIANCE',start=date(2015,1,1),end=date(2019,8,26))
data7=NSE.get_history(symbol='TCS',start=date(2015,1,1),end=date(2019,8,26))
data8=NSE.get_history(symbol='SBIN',start=date(2015,1,1),end=date(2019,8,26))
data9=NSE.get_history(symbol='LT',start=date(2015,1,1),end=date(2019,8,26))
data10=NSE.get_history(symbol='TITAN',start=date(2015,1,1),end=date(2019,8,26))
data11=NSE.get_history(symbol='UPL',start=date(2015,1,1),end=date(2019,8,26))
data12=NSE.get_history(symbol='TECHM',start=date(2015,1,1),end=date(2019,8,26))
data13=NSE.get_history(symbol='VEDL',start=date(2015,1,1),end=date(2019,8,26))
data14=NSE.get_history(symbol='ONGC',start=date(2015,1,1),end=date(2019,8,26))
data15=NSE.get_history(symbol='POWERGRID',start=date(2015,1,1),end=date(2019,8,26))
data16=NSE.get_history(symbol='WIPRO',start=date(2015,1,1),end=date(2019,8,26))
data17=NSE.get_history(symbol='SUNPHARMA',start=date(2015,1,1),end=date(2019,8,26))
data18=NSE.get_history(symbol='ZEEL',start=date(2015,1,1),end=date(2019,8,26))
data19=NSE.get_history(symbol='MARUTI',start=date(2015,1,1),end=date(2019,8,26))
data20=NSE.get_history(symbol='TATAMOTORS',start=date(2015,1,1),end=date(2019,8,26))
data21=NSE.get_history(symbol='TATASTEEL',start=date(2015,1,1),end=date(2019,8,26))
data22=NSE.get_history(symbol='IOC',start=date(2015,1,1),end=date(2019,8,26))
data23=NSE.get_history(symbol='ITC',start=date(2015,1,1),end=date(2019,8,26))
data24=NSE.get_history(symbol='HDFC',start=date(2015,1,1),end=date(2019,8,26))
data25=NSE.get_history(symbol='NTPC',start=date(2015,1,1),end=date(2019,8,26))
data26=NSE.get_history(symbol='JSWSTEEL',start=date(2015,1,1),end=date(2019,8,26))
data27=NSE.get_history(symbol='BPCL',start=date(2015,1,1),end=date(2019,8,26))
data28=NSE.get_history(symbol='ASIANPAINT',start=date(2015,1,1),end=date(2019,8,26))
data29=NSE.get_history(symbol='AXISBANK',start=date(2015,1,1),end=date(2019,8,26))
data30=NSE.get_history(symbol='CIPLA',start=date(2015,1,1),end=date(2019,8,26))
data31=NSE.get_history(symbol='BAJFINANCE',start=date(2015,1,1),end=date(2019,8,26))
data32=NSE.get_history(symbol='BAJAJ-AUTO',start=date(2015,1,1),end=date(2019,8,26))

data34=NSE.get_history(symbol='BAJAJFINSV',start=date(2015,1,1),end=date(2019,8,26))
data35=NSE.get_history(symbol='INFRATEL',start=date(2015,1,1),end=date(2019,8,26))
data36=NSE.get_history(symbol='BHARTIARTL',start=date(2015,1,1),end=date(2019,8,26))
data37=NSE.get_history(symbol='GAIL',start=date(2015,1,1),end=date(2019,8,26))
data38=NSE.get_history(symbol='GRASIM',start=date(2015,1,1),end=date(2019,8,26))
data39=NSE.get_history(symbol='HCLTECH',start=date(2015,1,1),end=date(2019,8,26))
data40=NSE.get_history(symbol='HDFCBANK',start=date(2015,1,1),end=date(2019,8,26))
data41=NSE.get_history(symbol='COALINDIA',start=date(2015,1,1),end=date(2019,8,26))
data42=NSE.get_history(symbol='DRREDDY',start=date(2015,1,1),end=date(2019,8,26))
data43=NSE.get_history(symbol='HINDALCO',start=date(2015,1,1),end=date(2019,8,26))
data44=NSE.get_history(symbol='BRITANNIA',start=date(2015,1,1),end=date(2019,8,26))
data45=NSE.get_history(symbol='INDUSINDBK',start=date(2015,1,1),end=date(2019,8,26))
data46=NSE.get_history(symbol='HINDUNILVR',start=date(2015,1,1),end=date(2019,8,26))
data47=NSE.get_history(symbol='IBULSGFIN',start=date(2015,1,1),end=date(2019,8,26))
data48=NSE.get_history(symbol='M&M',start=date(2015,1,1),end=date(2019,8,26))
data49=NSE.get_history(symbol='ULTRACEMCO',start=date(2015,1,1),end=date(2019,8,26))
data50=NSE.get_history(symbol='ICICIBANK',start=date(2015,1,1),end=date(2019,8,26))

datanew=pd.concat([data,data2,data3,data4,data5,data6,data7,data8,data9,data10,data11,data12,data13,data14,data15,data16,data17,data18,data19,data20,data21,data22,data23,data24,data25,data26,data27,data28,data29,data30,data31,data32,data34,data35,data36,data37,data38,data39,data40,data41,data42,data43,data44,data45,data46,data47,data48,data49,data50])

datanew['Symbol'].value_counts()
datanew

import numpy as np
arr=np.unique(datanew['Symbol'])

arr

arr.shape



